name: nf-LO
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - last=1060
  - lastz=1.0.4
  - minimap2=2.17
  - crossmap
  - GSAlign
  - ucsc-axtchain
  - ucsc-blat
  - ucsc-chainantirepeat
  - ucsc-chainmergesort
  - ucsc-chainnet
  - ucsc-chainprenet
  - ucsc-chainsplit
  - ucsc-chainstitchid
  - ucsc-fasplit
  - ucsc-fasize
  - ucsc-fatotwobit
  - ucsc-lavtopsl
  - ucsc-liftover
  - ucsc-liftup
  - ucsc-netchainsubset
  - ucsc-netsyntenic
  - ucsc-twobitinfo
  - zlib 
